var asset_tl=[{id:"tl",size:7,src:"images/tl.png"},{id:"tl_effect",size:7,src:"images/effect/tl_effect.png"}],asset_tl_16=[],asset_xh=[{id:"xh1",size:39,src:"images/xh1.png"},{id:"xh2",size:39,src:"images/xh2.png"},{id:"xh_effect1",size:1,src:"images/effect/xh_effect1.png"},{id:"xh_effect2",size:2,src:"images/effect/xh_effect2.png"}],asset_xh_16=[],asset_xm=[{id:"xm1",size:153,src:"images/xm1.png"},{id:"xm2",size:153,src:"images/xm2.png"},{id:"xm_effect",size:24,src:"images/effect/xm_effect.png"}],
asset_xm_16=[],asset_wood=[{id:"woodman1",size:11,src:"images/woodman1.png"},{id:"woodman2",size:11,src:"images/woodman2.png"},{id:"woodman_effect",size:11,src:"images/effect/woodman_effect.png"}],asset_wood_16=[],asset_effect=[],asset_newbie=[{id:"fightBg",size:11,src:"images/fightBg.png"},{id:"skill_9",size:11,src:"images/effect/skill_9.png"},{id:"skill_9_d",size:11,src:"images/effect/skill_9_d.png"},{id:"skill_14",size:11,src:"images/effect/skill_14.png"},{id:"skill_15",size:11,src:"images/effect/skill_15.png"},
{id:"skill_15_d",size:11,src:"images/effect/skill_15_d.png"},{id:"skill_7",size:11,src:"images/effect/skill_7.png"},{id:"Head_6_1",size:11,src:"images/equip/Head/Head_6_1.png"},{id:"Head_15_2",size:11,src:"images/equip/Head/Head_15_2.png"},{id:"Head_17_2",size:11,src:"images/equip/Head/Head_17_2.png"},{id:"Head_24_2",size:11,src:"images/equip/Head/Head_24_2.png"},{id:"Head_23_3",size:11,src:"images/equip/Head/Head_23_3.png"},{id:"Head_28_3",size:11,src:"images/equip/Head/Head_28_3.png"},{id:"Head_32",
size:11,src:"images/equip/Head/Head_32.png"},{id:"HandO_6_1",size:11,src:"images/equip/HandO/HandO_6_1.png"},{id:"HandI_6_1",size:11,src:"images/equip/HandI/HandI_6_1.png"},{id:"HandO_8_1",size:11,src:"images/equip/HandO/HandO_8_1.png"},{id:"HandI_8_1",size:11,src:"images/equip/HandI/HandI_8_1.png"},{id:"HandO_15_2",size:11,src:"images/equip/HandO/HandO_15_2.png"},{id:"HandI_15_2",size:11,src:"images/equip/HandI/HandI_15_2.png"},{id:"HandO_24_1",size:11,src:"images/equip/HandO/HandO_24_1.png"},{id:"HandI_24_1",
size:11,src:"images/equip/HandI/HandI_24_1.png"},{id:"HandO_28_3",size:11,src:"images/equip/HandO/HandO_28_3.png"},{id:"HandI_28_3",size:11,src:"images/equip/HandI/HandI_28_3.png"},{id:"HandO_23_3",size:11,src:"images/equip/HandO/HandO_23_3.png"},{id:"HandI_23_3",size:11,src:"images/equip/HandI/HandI_23_3.png"},{id:"HandO_32",size:11,src:"images/equip/HandO/HandO_32.png"},{id:"HandI_32",size:11,src:"images/equip/HandI/HandI_32.png"},{id:"Body_13",size:11,src:"images/equip/Body/Body_13.png"},{id:"Body_24",
size:11,src:"images/equip/Body/Body_24.png"},{id:"Body_28",size:11,src:"images/equip/Body/Body_28.png"},{id:"Body_23",size:11,src:"images/equip/Body/Body_23.png"},{id:"Body_32",size:11,src:"images/equip/Body/Body_32.png"},{id:"Arm_13",size:11,src:"images/equip/Arm/Arm_13.png"},{id:"Arm_11",size:11,src:"images/equip/Arm/Arm_11.png"},{id:"Arm_28",size:11,src:"images/equip/Arm/Arm_28.png"},{id:"Arm_23",size:11,src:"images/equip/Arm/Arm_23.png"},{id:"Arm_32",size:11,src:"images/equip/Arm/Arm_32.png"},
{id:"Foot_6",size:11,src:"images/equip/Foot/Foot_6.png"},{id:"Foot_17",size:11,src:"images/equip/Foot/Foot_17.png"},{id:"Foot_24",size:11,src:"images/equip/Foot/Foot_24.png"},{id:"Foot_28",size:11,src:"images/equip/Foot/Foot_28.png"},{id:"Foot_23",size:11,src:"images/equip/Foot/Foot_23.png"},{id:"Foot_32",size:11,src:"images/equip/Foot/Foot_32.png"}],asset_effect_16=[],asset_logo2=[{id:"loadingp",size:7,src:"images/loadingp.png"},{id:"shade",size:7,src:"images/shade.png"},{id:"substarate",size:7,
src:"images/substarate.jpg"},{id:"resource_1",size:279,src:"images/resource_1.png"},{id:"resource_2",size:412,src:"images/resource_2.png"},{id:"resource_3",size:69,src:"images/resource_3.png"},{id:"resource_10",size:25,src:"images/resource_10.png"},{id:"resource_12",size:25,src:"images/resource_12.png"},{id:"substarate0",size:6,src:"images/substarate0.png"},{id:"shengbai",size:52,src:"images/shengbai.png"},{id:"main",size:98,src:"images/main.jpg"},{id:"loadingN",size:11,src:"images/loadingN.jpg"},
{id:"loading",size:11,src:"images/loading.png"},{id:"loadingShadow",size:11,src:"images/loadingShadow.png"},{id:"plus",size:3,src:"images/fightNum_g.png"},{id:"tanchutiao",size:1,src:"images/tanchutiao.png"},{id:"minus",size:3,src:"images/fightNum_r.png"}],asset_logo=[{id:"openLogo",size:11,src:"images/openLogo.png"}];
