(function(m){var k=function(a,e,d,f,c,g){this.initialize(a,e,d,f,c,g)},b=k.prototype;k.identity=null;k.DEG_TO_RAD=Math.PI/180;b.a=1;b.b=0;b.c=0;b.d=1;b.tx=0;b.ty=0;b.alpha=1;b.shadow=null;b.compositeOperation=null;b.initialize=function(a,e,d,f,c,g){if(a!=null)this.a=a;this.b=e||0;this.c=d||0;if(f!=null)this.d=f;this.tx=c||0;this.ty=g||0;return this};b.prepend=function(a,e,d,f,c,g){var b=this.tx;if(a!=1||e!=0||d!=0||f!=1){var i=this.a,l=this.c;this.a=i*a+this.b*d;this.b=i*e+this.b*f;this.c=l*a+this.d*
d;this.d=l*e+this.d*f}this.tx=b*a+this.ty*d+c;this.ty=b*e+this.ty*f+g;return this};b.append=function(a,e,d,f,c,b){var h=this.a,i=this.b,l=this.c,j=this.d;this.a=a*h+e*l;this.b=a*i+e*j;this.c=d*h+f*l;this.d=d*i+f*j;this.tx=c*h+b*l+this.tx;this.ty=c*i+b*j+this.ty;return this};b.prependMatrix=function(a){this.prepend(a.a,a.b,a.c,a.d,a.tx,a.ty);this.prependProperties(a.alpha,a.shadow,a.compositeOperation);return this};b.appendMatrix=function(a){this.append(a.a,a.b,a.c,a.d,a.tx,a.ty);this.appendProperties(a.alpha,
a.shadow,a.compositeOperation);return this};b.prependTransform=function(a,e,d,f,c,b,h,i,l){if(c%360)var j=c*k.DEG_TO_RAD,c=Math.cos(j),j=Math.sin(j);else c=1,j=0;if(i||l)this.tx-=i,this.ty-=l;b||h?(b*=k.DEG_TO_RAD,h*=k.DEG_TO_RAD,this.prepend(c*d,j*d,-j*f,c*f,0,0),this.prepend(Math.cos(h),Math.sin(h),-Math.sin(b),Math.cos(b),a,e)):this.prepend(c*d,j*d,-j*f,c*f,a,e);return this};b.appendTransform=function(a,e,d,b,c,g,h,i,l){if(c%360)var j=c*k.DEG_TO_RAD,c=Math.cos(j),j=Math.sin(j);else c=1,j=0;g||
h?(g*=k.DEG_TO_RAD,h*=k.DEG_TO_RAD,this.append(Math.cos(h),Math.sin(h),-Math.sin(g),Math.cos(g),a,e),this.append(c*d,j*d,-j*b,c*b,0,0)):this.append(c*d,j*d,-j*b,c*b,a,e);if(i||l)this.tx-=i*this.a+l*this.c,this.ty-=i*this.b+l*this.d;return this};b.rotate=function(a){var e=Math.cos(a),a=Math.sin(a),d=this.a,b=this.c,c=this.tx;this.a=d*e-this.b*a;this.b=d*a+this.b*e;this.c=b*e-this.d*a;this.d=b*a+this.d*e;this.tx=c*e-this.ty*a;this.ty=c*a+this.ty*e;return this};b.skew=function(a,e){a*=k.DEG_TO_RAD;e*=
k.DEG_TO_RAD;this.append(Math.cos(e),Math.sin(e),-Math.sin(a),Math.cos(a),0,0);return this};b.scale=function(a,e){this.a*=a;this.d*=e;this.c*=a;this.b*=e;this.tx*=a;this.ty*=e;return this};b.translate=function(a,e){this.tx+=a;this.ty+=e;return this};b.regPoint=function(a,e){this.tx-=a*this.a+e*this.c;this.ty-=a*this.b+e*this.d};b.createBox=function(a,e,b,f,c,g,h){this.identity();var i=b;g==true&&(i*=-1);h==true&&(b*=-1);this.appendTransform(a,e,i,b,0,null,null,f,c)};b.identity=function(){this.alpha=
this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;this.shadow=this.compositeOperation=null;return this};b.invert=function(){var a=this.a,e=this.b,b=this.c,f=this.d,c=this.tx,g=a*f-e*b;this.a=f/g;this.b=-e/g;this.c=-b/g;this.d=a/g;this.tx=(b*this.ty-f*c)/g;this.ty=-(a*this.ty-e*c)/g;return this};b.isIdentity=function(){return this.tx==0&&this.ty==0&&this.a==1&&this.b==0&&this.c==0&&this.d==1};b.decompose=function(a){a==null&&(a={});a.x=this.tx;a.y=this.ty;a.scaleX=Math.sqrt(this.a*this.a+this.b*this.b);
a.scaleY=Math.sqrt(this.c*this.c+this.d*this.d);var b=Math.atan2(-this.c,this.d),d=Math.atan2(this.b,this.a);b==d?(a.rotation=d/k.DEG_TO_RAD,this.a<0&&this.d>=0&&(a.rotation+=a.rotation<=0?180:-180),a.skewX=a.skewY=0):(a.skewX=b/k.DEG_TO_RAD,a.skewY=d/k.DEG_TO_RAD);return a};b.reinitialize=function(a,b,d,f,c,g,h,i,l){this.initialize(a,b,d,f,c,g);this.alpha=h||1;this.shadow=i;this.compositeOperation=l;return this};b.appendProperties=function(a,b,d){this.alpha*=a;this.shadow=b||this.shadow;this.compositeOperation=
d||this.compositeOperation;return this};b.prependProperties=function(a,b,d){this.alpha*=a;this.shadow=this.shadow||b;this.compositeOperation=this.compositeOperation||d;return this};b.clone=function(){var a=new k(this.a,this.b,this.c,this.d,this.tx,this.ty);a.shadow=this.shadow;a.alpha=this.alpha;a.compositeOperation=this.compositeOperation;return a};b.toString=function(){return"[Matrix2D (a="+this.a+" b="+this.b+" c="+this.c+" d="+this.d+" tx="+this.tx+" ty="+this.ty+")]"};b.transformSize=function(a,
b){var d=a*this.a,f=a*this.b,c=b*this.c,g=b*this.d,h=d+c,i=f+g,l=Math.min(Math.min(0,d),Math.min(c,h)),d=Math.max(Math.max(0,d),Math.max(c,h)),c=Math.min(Math.min(0,f),Math.min(g,i)),f=Math.max(Math.max(0,f),Math.max(g,i));return{width:d-l+0.5>>0,height:f-c+0.5>>0}};b.getScaleX=function(){return Math.sqrt(this.a*this.a+this.c*this.c)};b.getScaleY=function(){return Math.sqrt(this.b*this.b+this.d*this.d)};b.getRotation=function(){return Math.atan(-this.c/this.a)};b.getSkewY=function(){return Math.atan2(this.b,
this.a)*(180/Math.PI)};b.getSkewX=function(){return Math.atan2(-this.c,this.d)*(180/Math.PI)};k.identity=new k(1,0,0,1,0,0);k.getBoundsAfterTransformation=function(a,b,d){function f(a,b){return{x:a.a*b.x+a.c*b.y+a.tx,y:a.b*b.x+a.d*b.y+a.ty}}var c={x:0,y:0},g={x:a,y:0},h={x:0,y:b},a={x:a,y:b},c=f(d,c),g=f(d,g),h=f(d,h),a=f(d,a),d=Math.min(c.x,g.x,h.x,a.x),b=Math.min(c.y,g.y,h.y,a.y),i=Math.max(c.x,g.x,h.x,a.x),c=Math.max(c.y,g.y,h.y,a.y);return[d,b,i-d,c-b]};m.Matrix2D=k})(window);
