(function(){var d=function(a){this.playerId=a;this.requestMsg=[];this.skills=[];this.weapons=[];this.gears=[];this.props=[];this.messages=[];this.qualifynews=[];this.requestMsg=[];this.messageBox=[];this.newMsg=false;this.friends=[];this.prentices=[];this.randomPlayer=[];this.stages=null;this.arenaType="";this.propsStates=null;this.isVIP=this.isStageRefresh=true;this.uc_vip=false;this.loginData={};this.levelRewards=null;this.rankMsgPage=this.msgPage=this.friendPage=1;this.rank_FirstJoin=false;this.arenaUseProp=
0;this.highestStageId=1;this.joinRankCount=this.woodRecord=null;this.isRandom=this.isRecruit=0;this.newbie=newbie_State.Loading};d.prototype.setLoginData=function(a){this.joinRankCount=a.joinRankCount||0;Q.merge(this.loginData,a)};d.prototype.getBase=function(){return this.baseData};d.prototype.getActiveStates=function(){var a=[],b;for(b in this.propsStates)this.propsStates[b]>0&&a.push(b);return a};d.prototype.parseRequest=function(a){this.requestMsg=[];for(var b in a)this.addRequest(a[b])};d.prototype.addRequest=
function(a){a.friendsMasterId!=this.playerId&&this.requestMsg.push(a)};d.prototype.getRequest=function(){return this.requestMsg};d.prototype.updateState=function(){for(var a in this.propsStates)this.propsStates[a]>0&&(this.propsStates[a]--,this.propsStates[a]==0&&JsonLoader.loadPlayerState())};d.prototype.setData=function(a){this.baseData={skillPoint:0,weaponPoint:0,goldPoint:0,goldCup:0};this.skills=[];this.weapons=[];this.gears=[];this.props=[];this.prentices=[];this.propsStates=this.stages=null;
this.isStageRefresh=true;this.uc_vip=this.isVIP=false;var b,c;for(c in a)switch(b=a[c],c){case "skills":this.setSkills(b);break;case "weapons":this.setWeapons(b);break;case "gears":this.setGears(b);break;case "props":this.parseProps(b);break;case "stages":this.parseStages(b);break;case "state":this.setState(b);break;case "wears":this.wearsMap=this.parseWears(b);this.wears=b;break;case "prentices":this.prentices=b;break;case "uc_vip":this.uc_vip=b;break;case "vip":this.isVIP=b;break;default:this.baseData[c]=
b}a=parseInt(game.player.getBase().level);if(game.player.loginData.reborn==0)switch(a){case 1:this.newbie=newbie_State.FirstBattle;break;case 2:this.newbie=newbie_State.Lvl2;break;case 3:this.newbie=game.player.getBase().energy<game.player.getBase().maxEnergy&&game.player.getBase().smallEnergy==0&&game.player.getPropById(1)!=void 0?newbie_State.UseProp:newbie_State.Lvl3;break;case 4:this.newbie=13;break;case 5:case 6:case 7:case 8:case 9:this.newbie=newbie_State.Lvl5;break;case 10:this.newbie=newbie_State.Lvl10;
break;default:this.newbie=newbie_State.Lvl10}else game.player.newbie=20};d.prototype.setPower=function(a){this.baseData.power=isNaN(a)?this.baseData.power:parseInt(a)};d.prototype.setAgility=function(a){this.baseData.agility=isNaN(a)?this.baseData.agility:parseInt(a)};d.prototype.setSpeed=function(a){this.baseData.speed=isNaN(a)?this.baseData.speed:parseInt(a)};d.prototype.setMaxHp=function(a){this.baseData.maxHp=isNaN(a)?this.baseData.maxHp:parseInt(a)};d.prototype.setEnergy=function(a){this.baseData.energy=
isNaN(a)?this.baseData.energy:parseInt(a)};d.prototype.setGoldPoint=function(a){this.baseData.goldPoint=isNaN(a)?this.baseData.goldPoint:parseInt(a)};d.prototype.addGoldPoint=function(a){this.baseData.goldPoint+=isNaN(a)?0:parseInt(a)};d.prototype.addWeaponPoint=function(a){this.baseData.weaponPoint+=isNaN(a)?0:parseInt(a)};d.prototype.addSkillPoint=function(a){this.baseData.skillPoint+=isNaN(a)?0:parseInt(a)};d.prototype.setSkills=function(a){for(var a=a.split("|"),b,c=0;c<a.length;c++)b=a[c],b!=
""&&this.addSkills(b)};d.prototype.getSkills=function(a){return a===false?this.skills:k(skillsMap.toArray(),this.skills)};d.prototype.setWeapons=function(a){for(var a=a.split("|"),b,c=0;c<a.length;c++)b=a[c],b!=""&&this.addWeapons(b)};d.prototype.getWeapons=function(a){return a===false?this.weapons:k(weaponsMap.toArray(),this.weapons)};d.prototype.setGears=function(a){for(var a=a.split("|"),b,c=0;c<a.length;c++)b=a[c],b!=""&&this.addGears(b)};d.prototype.parseWears=function(a){var b=new Map;b.put(0,
null);b.put(1,null);b.put(2,null);b.put(3,null);b.put(4,null);b.put(5,null);if(a!=void 0&&a!="0")for(var a=a.split(";"),c,e=0;e<a.length;e++)c=a[e],c!=""&&this.addWear(c,b);return b};d.prototype.getGears=function(){return this.gears};d.prototype.parseProps=function(a,b){for(var c=a.split("|"),e,d=b==false?[]:null,f=0;f<c.length;f++)e=c[f],e!=""&&this.addProps(e,d);return d};d.prototype.getAllProps=function(a){if(a===true){for(var a=[],b=0;b<this.props.length;b++)parseInt(this.props[b].useType)>0&&
a.push(this.props[b]);return a}return this.props};d.prototype.setFriends=function(a,b){this.friends=[];var c,e,d,f;if(a!=void 0&&a.length>0){c=a.split("|");for(f=0;f<c.length;f++)if(e=c[f],e!="")d=e.split(","),e={},e.id=d[0],e.name=d[1],e.level=d[2],e.relation=d[3],e.activity=d[4],e.power=d[5],e.agility=d[6],e.speed=d[7],e.hp=d[8],e.equip=d[9],e.vip=d[10],e.vipLevel=d[11],e.woodmanRecord=d[12],this.friends.push(e)}if(b!=void 0&&b.length>0){c=b.split("|");for(f=0;f<c.length;f++)e=c[f],e!=""&&(d=e.split(","),
e={ucId:d[0],name:d[1],invited:0},this.friends.push(e))}};d.prototype.getFriends=function(){return this.friends};d.prototype.delFriendById=function(a){for(i=0;i<this.friends.length;i++)if(item=this.friends[i],item.id==a)return this.friends.splice(i,1),true;return false};d.prototype.setRandom=function(a){if(a!=""){var a=a.split("|"),b,c;this.randomPlayer=[];for(var e=0;e<a.length;e++)if(b=a[e],b!="")c=b.split(","),b={},b.id=c[0],b.name=c[1],b.level=c[2],b.relation=c[3],b.activity=c[4],b.power=c[5],
b.agility=c[6],b.speed=c[7],b.hp=c[8],b.equip=c[9],b.vip=c[10],b.vipLevel=c[11],b.woodmanRecord=c[12],this.randomPlayer.push(b)}};d.prototype.getRandom=function(){return this.randomPlayer};d.prototype.getPropById=function(a){for(var b,c=0;c<this.props.length;c++)if(b=this.props[c],b.id==a)return b;return null};d.prototype.getWeaponById=function(a){for(var b,c=0;c<this.weapons.length;c++)if(b=this.weapons[c],b.id==a)return b;return null};d.prototype.getSkillById=function(a){for(var b,c=0;c<this.skills.length;c++)if(b=
this.skills[c],b.id==a)return b;return null};d.prototype.deleteProps=function(a){for(var b=a.id,c=a.count,e,a=0;a<this.props.length;a++)if(e=this.props[a],e.id==b){b=parseInt(e.num)-c;b>0?this.props[a].num=b:this.props.splice(a,1);break}};d.prototype.addProps=function(a,b){if(typeof a=="string")var c=a.split(":"),e=isNaN(c[0])?-1:parseInt(c[0]),c=isNaN(c[1])?0:parseInt(c[1]),a={id:e,num:c};if(b==void 0||b==null){if(a.id==21)this.baseData.skillPoint=isNaN(this.baseData.skillPoint)?parseInt(a.num):
this.baseData.skillPoint+parseInt(a.num),this.baseData.skillPoint=Math.min(this.baseData.skillPoint,9999);else if(a.id==22)this.baseData.weaponPoint=isNaN(this.baseData.weaponPoint)?parseInt(a.num):this.baseData.weaponPoint+parseInt(a.num),this.baseData.weaponPoint=Math.min(this.baseData.weaponPoint,9999);else if(a.id==8)this.baseData.goldPoint=isNaN(this.baseData.goldPoint)?parseInt(a.num):this.baseData.goldPoint+parseInt(a.num);else if(a.id==15)this.baseData.exp+=parseInt(a.num);else if(a.id==40)this.baseData.goldCup=
isNaN(this.baseData.goldCup)?parseInt(a.num):this.baseData.goldCup+parseInt(a.num),this.baseData.goldCup=Math.min(this.baseData.goldCup,9999);for(e=0;e<this.props.length;e++)if(this.props[e].id==a.id){this.props[e].num=parseInt(this.props[e].num)+a.num;this.props[e].num=Math.min(this.props[e].num,9999);return}}(e=propMap.getValue(a.id))&&Q.merge(a,e);b==void 0||b==null?this.props.push(a):b.push(a)};d.prototype.addSkills=function(a){if(typeof a=="string")var b=a.split(":"),a=isNaN(b[0])?-1:parseInt(b[0]),
b=isNaN(b[1])?0:parseInt(b[1]),a={id:a,level:b};(b=skillsMap.getValue(a.id))&&Q.merge(a,b);this.skills.push(a)};d.prototype.deleteSkills=function(a){for(var b in this.skills)this.skills[b].id==a&&this.skills.splice(b,1)};d.prototype.addWeapons=function(a){if(typeof a=="string")var b=a.split(":"),a=isNaN(b[0])?-1:parseInt(b[0]),b=isNaN(b[1])?0:parseInt(b[1]),a={id:a,level:b};if(b=weaponsMap.getValue(a.id)){Q.merge(a,b);var b=a,c=b.harm.split("-"),e;if(b.level<=10)e=parseInt(b.harmAdd)*(b.level-1);
else{e=parseInt(b.harmAdd)*9;for(var d=b.harmAdd1.split("|"),f=Number(b.level)-10,h=0;h<f;h++)e+=Number(d[h])}b.harm=parseInt(c[0])+e+"-"+(parseInt(c[1])+e)}this.weapons.push(a)};d.prototype.deleteWeapons=function(a){for(var b in this.weapons)this.weapons[b].id==a&&this.weapons.splice(b,1)};d.prototype.addGears=function(a){var b=[].slice.call(arguments);typeof a=="string"&&(b=a.split(":"));var c={id:b.shift(),used:b.shift()=="true",key:b.shift()};if(b.length>0)for(var d=[],g=0,f,h,j;b.length>0;){h=
parseInt(b.shift());f=parseInt(b.shift());g=Math.max(g,f);j=attachmentMap.getValue(h);h={id:h,level:f};if(j)f=j.ability.split(",")[f-1],h.content=j.name.replace("N",f);d.push(h);c.maxLevel=g;c.ext=d}b=gearMap.getValue(c.id);d=gearSetMap.getValue(b.setId);c.name=b.name;c.price=parseInt(d.price);g=parseInt(b.type);c.ability=["\u654f\u6377","\u529b\u91cf","\u751f\u547d","\u901f\u5ea6"][g]+"+"+b.abilities.split(",")[g];c.useLevel=parseInt(d.level);c.image=BitmapFactory.getEquipImageData(g,d.index,c.maxLevel);
this.gears.push(c);return c};d.prototype.deleteGears=function(){for(var a=[].slice.call(arguments),b=0;b<a.length;b++)this.deleteGearsByKey(a[b])};d.prototype.deleteGearsByKey=function(a){for(var b=0;b<this.gears.length;b++)if(this.gears[b].key==a){this.gears.splice(b,1);break}};d.prototype.addWear=function(a,b){var c,d,g;if(typeof a=="string"){g=a.split(":");c=g.shift();d=void 0;for(var f=0;g.length>2;)parseInt(g.shift()),d=parseInt(g.shift()),d=f=Math.max(f,d)}else c=a.id,d=a.maxLevel;g=gearMap.getValue(c);
c=gearSetMap.getValue(g.setId);f=parseInt(g.type);g=BitmapFactory.getEquipImageData(f,c.index,d);b.put(f,g);f==1?b.put(4,BitmapFactory.getEquipImageData(4,c.index,d)):f==2&&b.put(5,BitmapFactory.getEquipImageData(5,c.index,d))};d.prototype.addMyWear=function(a){this.addWear(a,this.wearsMap)};d.prototype.getWears=function(){return this.wearsMap};d.prototype.removeGear=function(a){a==1||a==4?(this.wearsMap.put(1,null),this.wearsMap.put(4,null)):a==2||a==5?(this.wearsMap.put(2,null),this.wearsMap.put(5,
null)):this.wearsMap.put(a,null)};d.prototype.changeFriendRelation=function(a){for(var b=a.id,a=a.relation,c=0;c<this.friends.length;c++)if(this.friends[c].id==b){this.friends[c].relation=a;break}for(c=0;c<this.randomPlayer.length;c++)if(this.randomPlayer[c].id==b){this.randomPlayer[c].relation=a;break}};d.prototype.setState=function(a){this.propsStates={};for(var a=a.split(","),b=[3,4,5,7,41,42,43,44],c=0;c<a.length;c++)this.propsStates[b[c]]=a[c]};d.prototype.setNewState=function(a,b){this.propsStates[a]=
b===void 0?20:parseInt(b)};d.prototype.reset=function(){this.skills=[];this.weapons=[]};d.prototype.updatePrenticesByid=function(a,b){var c=ArrayUtil.indexOfKey(this.prentices,"id",a.id);if(b==true&&c==-1)return this.prentices.push(a),true;return b==false&&c!=-1?(this.prentices.splice(c),true):false};d.prototype.parseStages=function(a){this.stages=new Map;(a==void 0||a.length==0)&&this.stages.put(1,{stageId:1,passed:false,keep:false,npcIndex:1,revive:false});if(a instanceof Array)for(var b=0;b<a.length;b++){if(a[b].passed==
true&&a[b].stageId>=game.player.highestStageId)game.player.highestStageId=a[b].stageId+1;this.stages.put(a[b].stageId,a[b])}};var k=function(a,b){for(var c,d=[],g=0;g<a.length;g++)c=ArrayUtil.indexOfKey(b,"id",a[g].id),c===-1?d.push(a[g]):d.push(b[c]);return d};window.player=d})();
