(function(b){function a(a,d,c){for(var b=a.length,k=d.length,j,i,p,o,r,m,l=0,n=j=0;n<b;n++){j=a[n];i=a[n<b-1?n+1:0];l=j.y-i.y;j=i.x-j.x;i=Math.sqrt(l*l+j*j);l/=i;j/=i;i=p=a[0].x*l+a[0].y*j;for(var q=1;q<b;q++)m=a[q].x*l+a[q].y*j,m>p?p=m:m<i&&(i=m);o=r=d[0].x*l+d[0].y*j;for(q=1;q<k;q++)m=d[q].x*l+d[q].y*j,m>r?r=m:m<o&&(o=m);i<o?(i=o-p,l=-l,j=-j):i-=r;if(i>=0)return false;else if(i>c.overlap)c.overlap=i,c.normal.x=l,c.normal.y=j}return c}var d=b.Quark=b.Quark||{global:b,scale:1},c=function(){};d.inherit=
function(a,d){c.prototype=d.prototype;a.superClass=d.prototype;a.prototype=new c;a.prototype.constructor=a};d.merge=function(a,d,c){for(var b in d)if(!c||a.hasOwnProperty(b)||a[b]!==void 0)a[b]=d[b];return a};d.delegate=function(a,d){var c=d||b;if(arguments.length>2){var g=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.concat.apply(g,arguments);return a.apply(c,d)}}else return function(){return a.apply(c,arguments)}};d.use=function(a){for(var a=a.split("."),d=b,c=
0;c<a.length;c++)var g=a[c],d=d[g]||(d[g]={});return d};d.DEG_TO_RAD=Math.PI/180;d.RAD_TO_DEG=180/Math.PI;d.hitTestPoint=function(a,d,c,b){var a=a.getBounds(),k=a.length,j=d>=a.x&&d<=a.x+a.width&&c>=a.y&&c<=a.y+a.height;if(j&&b){for(var b=0,j=false,i,p,o,r,m=0;m<k;m++){var l=a[m],n=a[(m+1)%k];if(l.y==n.y&&c==l.y&&(l.x>n.x?(i=n.x,p=l.x):(i=l.x,p=n.x),d>=i&&d<=p)){j=true;continue}l.y>n.y?(o=n.y,r=l.y):(o=l.y,r=n.y);c<o||c>r||(l=(c-l.y)*(n.x-l.x)/(n.y-l.y)+l.x,l>d?b++:l==d&&(j=true))}if(j)return 0;else if(b%
2==1)return 1;return-1}return j?1:-1};d.hitTestObject=function(a,c,b){a=a.getBounds();c=c.getBounds();return(a=a.x<=c.x+c.width&&c.x<=a.x+a.width&&a.y<=c.y+c.height&&c.y<=a.y+a.height)&&b?(a=d.polygonCollision(c,c),a!==false):a};d.polygonCollision=function(d,c){var b=a(d,c,{overlap:-Infinity,normal:{x:0,y:0}});return b?a(c,d,b):false};d.toString=function(){return"Quark"};d.trace=function(){var a=Array.prototype.slice.call(arguments);typeof console!="undefined"&&typeof console.log!="undefined"&&console.log(a.join(" "))};
if(b.Q==void 0)b.Q=d})(window);(function(){var b=Quark.Context=function(a){if(a.canvas==null)throw"Quark.Context Error: canvas is required.";this.canvas=null;Quark.merge(this,a)};b.prototype.startDraw=function(){};b.prototype.draw=function(){};b.prototype.endDraw=function(){};b.prototype.transform=function(){};b.prototype.remove=function(){}})();
(function(){var b=Quark.CanvasContext=function(a){b.superClass.constructor.call(this,a);this.context=this.canvas};Quark.inherit(b,Quark.Context);b.prototype.startDraw=function(){this.context.save()};b.prototype.draw=function(a){if(!(a.parent!=null&&a.parent.mask!=null))if(a._cache!=null)this.context.drawImage(a._cache,0,0);else if(a instanceof Quark.Text)a._draw(this.context);else{var d=a.getDrawable(this);d!=null&&(arguments[0]=d,this.context.drawImage.apply(this.context,arguments))}};b.prototype.endDraw=
function(){this.context.restore()};b.prototype.transform=function(a){var d=this.context;if(a instanceof Q.Stage){if(a._scaleX!=a.scaleX)a._scaleX=a.scaleX;if(a._scaleY!=a.scaleY)a._scaleY=a.scaleY}else{var c=a.matrix;c!=null?d.setTransform(c.a,c.b,c.c,c.d,c.tx,c.ty):((a.x!=0||a.y!=0)&&d.translate(a.x,a.y),a.rotation%360!=0&&d.rotate(a.rotation%360*Quark.DEG_TO_RAD),(a.scaleX!=1||a.scaleY!=1)&&d.scale(a.scaleX,a.scaleY),(a.regX!=0||a.regY!=0)&&d.translate(-a.regX,-a.regY))}a.alpha>0&&(d.globalAlpha*=
a.alpha)};b.prototype.clear=function(a,d,c,b){this.context.clearRect(a,d,c,b)}})();(function(){var b=Quark.UIDUtil={_counter:0};b.createUID=function(a){var d=a.charCodeAt(a.length-1);d>=48&&d<=57&&(a+="_");return a+this._counter++};b.displayObjectToString=function(a){for(var d;a!=null;a=a.parent){var c=a.id!=null?a.id:a.name;d=d==null?c:c+"."+d;if(a==a.parent)break}return d}})();
(function(){var b=Quark.Drawable=function(a,d){this.domDrawable=this.rawDrawable=null;this.set(a,d)};b.prototype.get=function(){return this.rawDrawable};b.prototype.set=function(a){this.rawDrawable=a}})();
(function(){var b=Quark.Rectangle=function(a,d,c,b){this.x=a;this.y=d;this.width=c;this.height=b};b.prototype.intersects=function(a){return this.x<=a.x+a.width&&a.x<=this.x+this.width&&this.y<=a.y+a.height&&a.y<=this.y+this.height};b.prototype.intersection=function(a){var d=Math.max(this.x,a.x),c=Math.min(this.x+this.width,a.x+a.width);if(d<=c){var e=Math.max(this.y,a.y),a=Math.min(this.y+this.height,a.y+a.height);if(e<=a)return new b(d,e,c-d,a-e)}return null};b.prototype.union=function(a,d){var c=
Math.max(this.x+this.width,a.x+a.width),e=Math.max(this.y+this.height,a.y+a.height),f=Math.min(this.x,a.x),h=Math.min(this.y,a.y);c-=f;e-=h;if(d)return new b(f,h,c,e);else this.x=f,this.y=h,this.width=c,this.height=e};b.prototype.containsPoint=function(a,d){return this.x<=a&&a<=this.x+this.width&&this.y<=d&&d<=this.y+this.height};b.prototype.clone=function(){return new b(this.x,this.y,this.width,this.height)};b.prototype.toString=function(){return"(x="+this.x+", y="+this.y+", width="+this.width+", height="+
this.height+")"}})();
(function(){var b=Quark.Timer=function(a){this.interval=a||50;this.paused=false;this.info={lastTime:0,currentTime:0,deltaTime:0,realDeltaTime:0};this._startTime=0;this._intervalID=null;this._listeners=[]};b.prototype.start=function(){if(this._intervalID==null){this._startTime=this.info.lastTime=this.info.currentTime=Date.now();var a=this,d=function(){a._intervalID=setTimeout(d,a.interval);a._run()};d()}};b.prototype.stop=function(){clearTimeout(this._intervalID);this._intervalID=null;this._startTime=
0};b.prototype.pause=function(){this.paused=true};b.prototype.resume=function(){this.paused=false};b.prototype._run=function(){if(!this.paused){var a=this.info,d=a.currentTime=Date.now();a.deltaTime=a.realDeltaTime=d-a.lastTime;for(var c=0,b=this._listeners.length,f,h;c<b;c++)f=this._listeners[c],h=f.__runTime||0,h==0?f.step(this.info):d>h&&(f.step(this.info),this._listeners.splice(c,1),c--,b--);a.lastTime=d}};b.prototype.delay=function(a,d){this.addListener({step:a,__runTime:Date.now()+d})};b.prototype.addListener=
function(a){if(a==null||typeof a.step!="function")throw"Timer Error: The listener object must implement a step() method!";this._listeners.push(a)};b.prototype.removeListener=function(a){a=this._listeners.indexOf(a);a>-1&&this._listeners.splice(a,1)}})();
(function(){var b=Quark.Tween=function(d,c,b){this.target=d;this.delay=this.time=0;this.reverse=this.loop=this.paused=false;this.interval=0;this.ease=a.Linear.EaseNone;this.onComplete=this.onUpdate=this.onStart=this.next=null;this._oldProps={};this._newProps={};this._deltaProps={};this._pausedStartTime=this._pausedTime=this._lastTime=this._startTime=0;this._reverseFlag=1;this._frameCount=this._frameTotal=0;for(var f in c){var h=d[f],g=c[f];h!==void 0&&typeof h=="number"&&typeof g=="number"&&(this._oldProps[f]=
h,this._newProps[f]=g,this._deltaProps[f]=g-h)}for(f in b)this[f]=b[f]};b.prototype.setProps=function(a,c){for(var b in a)this.target[b]=this._oldProps[b]=a[b];for(b in c)this._newProps[b]=c[b],this._deltaProps[b]=c[b]-this.target[b]};b.prototype._init=function(){this._startTime=Date.now()+this.delay;this._pausedTime=0;if(this.interval>0)this._frameTotal=Math.round(this.time/this.interval);b.add(this)};b.prototype.start=function(){this._init();this.paused=false};b.prototype.stop=function(){b.remove(this)};
b.prototype.pause=function(){this.paused=true;this._pausedStartTime=Date.now()};b.prototype.resume=function(){this.paused=false;this._pausedTime+=Date.now()-this._pausedStartTime};b.prototype._update=function(){if(!this.paused){var a=Date.now(),c=a-this._startTime-this._pausedTime;if(!(c<0)){if(this._lastTime==0&&this.onStart!=null)this.onStart(this);this._lastTime=a;a=this._frameTotal>0?++this._frameCount/this._frameTotal:c/this.time;a>1&&(a=1);var c=this.ease(a),e;for(e in this._oldProps)this.target[e]=
this._oldProps[e]+this._deltaProps[e]*this._reverseFlag*c;if(this.onUpdate!=null)this.onUpdate(this,c);if(a>=1){if(this.reverse){if(e=this._oldProps,this._oldProps=this._newProps,this._newProps=e,this._startTime=Date.now(),this._frameCount=0,this._reverseFlag*=-1,!this.loop)this.reverse=false}else if(this.loop){for(e in this._oldProps)this.target[e]=this._oldProps[e];this._startTime=Date.now();this._frameCount=0}else if(b.remove(this),e=this.next,e!=null&&(e instanceof b?(a=e,e=null):a=e.shift(),
a!=null))a.next=e,a.start();if(this.onComplete!=null)this.onComplete(this)}}}};b._tweens=[];b.step=function(){for(var a=this._tweens,c=a.length;--c>=0;)a[c]._update()};b.add=function(a){this._tweens.indexOf(a)==-1&&this._tweens.push(a);return this};b.remove=function(a){var c=this._tweens,a=c.indexOf(a);a>-1&&c.splice(a,1);return this};b.to=function(a,c,e){a=new b(a,c,e);a._init();return a};b.from=function(a,c,e){c=new b(a,c,e);e=c._oldProps;c._oldProps=c._newProps;c._newProps=e;c._reverseFlag=-1;
for(var f in c._oldProps)a[f]=c._oldProps[f];c._init();return c};var a=Quark.Easing={Linear:{},Quadratic:{},Cubic:{},Quartic:{},Quintic:{},Sinusoidal:{},Exponential:{},Circular:{},Elastic:{},Back:{},Bounce:{}};a.Linear.EaseNone=function(a){return a};a.Quadratic.EaseIn=function(a){return a*a};a.Quadratic.EaseOut=function(a){return-a*(a-2)};a.Quadratic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a:-0.5*(--a*(a-2)-1)};a.Cubic.EaseIn=function(a){return a*a*a};a.Cubic.EaseOut=function(a){return--a*a*a+
1};a.Cubic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a:0.5*((a-=2)*a*a+2)};a.Quartic.EaseIn=function(a){return a*a*a*a};a.Quartic.EaseOut=function(a){return-(--a*a*a*a-1)};a.Quartic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a:-0.5*((a-=2)*a*a*a-2)};a.Quintic.EaseIn=function(a){return a*a*a*a*a};a.Quintic.EaseOut=function(a){return(a-=1)*a*a*a*a+1};a.Quintic.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*a*a*a:0.5*((a-=2)*a*a*a*a+2)};a.Sinusoidal.EaseIn=function(a){return-Math.cos(a*Math.PI/
2)+1};a.Sinusoidal.EaseOut=function(a){return Math.sin(a*Math.PI/2)};a.Sinusoidal.EaseInOut=function(a){return-0.5*(Math.cos(Math.PI*a)-1)};a.Exponential.EaseIn=function(a){return a==0?0:Math.pow(2,10*(a-1))};a.Exponential.EaseOut=function(a){return a==1?1:-Math.pow(2,-10*a)+1};a.Exponential.EaseInOut=function(a){return a==0?0:a==1?1:(a*=2)<1?0.5*Math.pow(2,10*(a-1)):0.5*(-Math.pow(2,-10*(a-1))+2)};a.Circular.EaseIn=function(a){return-(Math.sqrt(1-a*a)-1)};a.Circular.EaseOut=function(a){return Math.sqrt(1-
--a*a)};a.Circular.EaseInOut=function(a){return(a/=0.5)<1?-0.5*(Math.sqrt(1-a*a)-1):0.5*(Math.sqrt(1-(a-=2)*a)+1)};a.Elastic.EaseIn=function(a){var c,b=0.1,f=0.4;if(a==0)return 0;else if(a==1)return 1;else f||(f=0.3);!b||b<1?(b=1,c=f/4):c=f/(2*Math.PI)*Math.asin(1/b);return-(b*Math.pow(2,10*(a-=1))*Math.sin((a-c)*2*Math.PI/f))};a.Elastic.EaseOut=function(a){var b,e=0.1,f=0.4;if(a==0)return 0;else if(a==1)return 1;else f||(f=0.3);!e||e<1?(e=1,b=f/4):b=f/(2*Math.PI)*Math.asin(1/e);return e*Math.pow(2,
-10*a)*Math.sin((a-b)*2*Math.PI/f)+1};a.Elastic.EaseInOut=function(a){var b,e=0.1,f=0.4;if(a==0)return 0;else if(a==1)return 1;else f||(f=0.3);!e||e<1?(e=1,b=f/4):b=f/(2*Math.PI)*Math.asin(1/e);return(a*=2)<1?-0.5*e*Math.pow(2,10*(a-=1))*Math.sin((a-b)*2*Math.PI/f):e*Math.pow(2,-10*(a-=1))*Math.sin((a-b)*2*Math.PI/f)*0.5+1};a.Back.EaseIn=function(a){return a*a*(2.70158*a-1.70158)};a.Back.EaseOut=function(a){return(a-=1)*a*(2.70158*a+1.70158)+1};a.Back.EaseInOut=function(a){return(a*=2)<1?0.5*a*a*
(3.5949095*a-2.5949095):0.5*((a-=2)*a*(3.5949095*a+2.5949095)+2)};a.Bounce.EaseIn=function(d){return 1-a.Bounce.EaseOut(1-d)};a.Bounce.EaseOut=function(a){return(a/=1)<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};a.Bounce.EaseInOut=function(d){return d<0.5?a.Bounce.EaseIn(d*2)*0.5:a.Bounce.EaseOut(d*2-1)*0.5+0.5}})();
(function(){var b=Quark.Matrix=function(a,d,b,e,f,h){this.a=a;this.b=d;this.c=b;this.d=e;this.tx=f;this.ty=h};b.prototype.concat=function(a){var d=this.a,b=this.c,e=this.tx;this.a=d*a.a+this.b*a.c;this.b=d*a.b+this.b*a.d;this.c=b*a.a+this.d*a.c;this.d=b*a.b+this.d*a.d;this.tx=e*a.a+this.ty*a.c+a.tx;this.ty=e*a.b+this.ty*a.d+a.ty;return this};b.prototype.rotate=function(a){var d=Math.cos(a),a=Math.sin(a),b=this.a,e=this.c,f=this.tx;this.a=b*d-this.b*a;this.b=b*a+this.b*d;this.c=e*d-this.d*a;this.d=
e*a+this.d*d;this.tx=f*d-this.ty*a;this.ty=f*a+this.ty*d;return this};b.prototype.scale=function(a,d){this.a*=a;this.d*=d;this.tx*=a;this.ty*=d;return this};b.prototype.translate=function(a,d){this.tx+=a;this.ty+=d;return this};b.prototype.identity=function(){this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;return this};b.prototype.invert=function(){var a=this.a,d=this.b,b=this.c,e=this.d,f=this.tx,h=a*e-d*b;this.a=e/h;this.b=-d/h;this.c=-b/h;this.d=a/h;this.tx=(b*this.ty-e*f)/h;this.ty=-(a*this.ty-
d*f)/h;return this};b.prototype.transformPoint=function(a,d,b){var e=a.x*this.a+a.y*this.c+this.tx,f=a.x*this.b+a.y*this.d+this.ty;d&&(e=e+0.5>>0,f=f+0.5>>0);if(b)return{x:e,y:f};a.x=e;a.y=f;return a};b.prototype.clone=function(){return new b(this.a,this.b,this.c,this.d,this.tx,this.ty)};b.prototype.toString=function(){return"(a="+this.a+", b="+this.b+", c="+this.c+", d="+this.d+", tx="+this.tx+", ty="+this.ty+")"}})();
(function(){var b=Quark.EventManager=function(){this.keyState={};this._evtHandlers={}};b.prototype.registerStage=function(a,d,b,e){this.register(a.context.canvas,d,{host:a,func:a._onEvent},b,e)};b.prototype.unregisterStage=function(a,d){this.unregister(a.context.canvas,d,a.onEvent)};b.prototype.register=function(a,d,b,e,f){if(b==null||typeof b=="function")b={host:null,func:b};for(var h={prevent:e,stop:f},g=this,e=function(a){g._onEvent(a,h,b)},f=0;f<d.length;f++){for(var k=d[f],j=this._evtHandlers[k]||
(this._evtHandlers[k]=[]),i=0,p=false;i<j.length;i++){var o=j[i];if(o.target==a&&o.callback.func==b.func){trace("duplicate callback");p=true;break}}p||(j.push({target:a,callback:b,handler:e}),a.addEventListener(k,e,false))}};b.prototype.unregister=function(a,b,c){for(var e=0;e<b.length;e++)for(var f=b[e],h=this._evtHandlers[f],g=0;g<h.length;g++){var k=h[g];if(k.target==a&&(k.callback.func==c||c==null)){a.removeEventListener(f,k.handler);h.splice(g,1);break}}};b.prototype._onEvent=function(a,b,c){a=
a.touches&&a.touches.length>0?a.touches[0]:a.changedTouches&&a.changedTouches.length>0?a.changedTouches[0]:a;c.func!=null&&c.func.call(c.host,a)};b.stop=function(a,b,c){b||a.preventDefault();c||(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation())}})();
(function(){var b=Quark.EventDispatcher=function(){this._eventMap={}};b.prototype.addEventListener=function(a,b){var c=this._eventMap[a];c==null&&(c=this._eventMap[a]=[]);return c.indexOf(b)==-1?(c.push(b),true):false};b.prototype.removeEventListener=function(a,b){var c=this._eventMap[a];if(c==null)return false;for(var e=0;e<c.length;e++)if(c[e]===b)return c.splice(e,1),c.length==0&&delete this._eventMap[a],true;return false};b.prototype.removeEventListenerByType=function(a){return this._eventMap[a]!=
null?(delete this._eventMap[a],true):false};b.prototype.removeAllEventListeners=function(){this._eventMap={}};b.prototype.dispatchEvent=function(a){var b=this._eventMap[a.type];if(b==null)return false;if(!a.target)a.target=this;for(var b=b.slice(),c=0;c<b.length;c++){var e=b[c];typeof e=="function"&&e.call(this,a)}return true};b.prototype.hasEventListener=function(a){a=this._eventMap[a];return a!=null&&a.length>0};b.prototype.on=b.prototype.addEventListener;b.prototype.un=b.prototype.removeEventListener;
b.prototype.fire=b.prototype.dispatchEvent})();
(function(){var b=Quark.DisplayObject=function(a){this.id=Quark.UIDUtil.createUID("DisplayObject");this.name=null;this.height=this.width=this.regY=this.regX=this.y=this.x=0;this.scaleY=this.scaleX=this.alpha=1;this.rotation=0;this.transformEnabled=this.eventEnabled=this.visible=true;this.useHandCursor=false;this.context=this.parent=this.drawable=this.matrix=this.mask=this.polyArea=null;this._depth=0;this._lastState={};this._stateList="x,y,regX,regY,width,height,alpha,scaleX,scaleY,rotation,visible,_depth".split(",");Quark.merge(this,
a,true);a.mixin&&Quark.merge(this,a.mixin,false)};b.prototype.setDrawable=function(a){this.drawable==null?this.drawable=new Quark.Drawable(a):this.drawable.rawDrawable!=a&&this.drawable.set(a)};b.prototype.getDrawable=function(a){return this._cache||this.drawable&&this.drawable.get(this,a)};b.prototype._update=function(a){this.update(a)};b.prototype.update=function(){return true};b.prototype._render=function(a){a=this.context||a;!this.visible||this.alpha<=0?(a.hide!=null&&a.hide(this),this.saveState(["visible",
"alpha"])):(a.startDraw(),a.transform(this),this.render(a),a.endDraw(),this.saveState())};b.prototype.render=function(a){a.draw(this,0,0,this.width,this.height,0,0,this.width,this.height)};b.prototype._onEvent=function(a){var b="on"+a.type;if(this[b]!=null)this[b](a)};b.prototype.onPress=null;b.prototype.saveState=function(){};b.prototype.getState=function(a){return this._lastState["last"+a]};b.prototype.propChanged=function(){for(var a=arguments.length>0?arguments:this._stateList,b=0,c=a.length;b<
c;b++){var e=a[b];if(this._lastState["last"+e]!=this[e])return true}return false};b.prototype.hitTestPoint=function(a,b,c){return Quark.hitTestPoint(this,a,b,c)};b.prototype.hitTestObject=function(a,b){return Quark.hitTestObject(this,a,b)};b.prototype.localToGlobal=function(a,b){var c=this.getConcatenatedMatrix();return{x:c.tx+a,y:c.ty+b}};b.prototype.globalToLocal=function(a,b){var c=this.getConcatenatedMatrix().invert();return{x:c.tx+a,y:c.ty+b}};b.prototype.localToTarget=function(a,b,c){a=this.localToGlobal(a,
b);return c.globalToLocal(a.x,a.y)};b.prototype.getConcatenatedMatrix=function(a){var b=new Quark.Matrix(1,0,0,1,0,0);if(a==this)return b;for(var c=this;c.parent!=null&&c.parent!=a;c=c.parent){var e=1,f=0;c.rotation%360!=0&&(f=c.rotation*Quark.DEG_TO_RAD,e=Math.cos(f),f=Math.sin(f));c.regX!=0&&(b.tx-=c.regX);c.regY!=0&&(b.ty-=c.regY);b.concat(new Quark.Matrix(e*c.scaleX,f*c.scaleX,-f*c.scaleY,e*c.scaleY,c.x,c.y))}return b};b.prototype.getBounds=function(){var a=this.width,b=this.height,c=this.getConcatenatedMatrix(),
a=this.polyArea||[{x:0,y:0},{x:a,y:0},{x:a,y:b},{x:0,y:b}],b=[],e=a.length,f,h,g,k,j;f=c.transformPoint(a[0],true,true);h=g=f.x;k=j=f.y;b[0]=f;for(var i=1;i<e;i++){f=c.transformPoint(a[i],true,true);if(h>f.x)h=f.x;else if(g<f.x)g=f.x;if(k>f.y)k=f.y;else if(j<f.y)j=f.y;b[i]=f}b.x=h;b.y=k;b.width=g-h;b.height=j-k;return b};b.prototype.getCurrentWidth=function(){return Math.abs(this.width*this.scaleX)};b.prototype.getCurrentHeight=function(){return Math.abs(this.height*this.scaleY)};b.prototype.getStage=
function(){for(var a=this;a.parent;)a=a.parent;return a instanceof Quark.Stage?a:null};Quark.DisplayObject.prototype.cache=function(a,b){return this._cache=Quark.cacheObject(this,a,b)};Quark.DisplayObject.prototype.uncache=function(){this._cache=null};Quark.DisplayObject.prototype.toImage=function(a){return Quark.cacheObject(this,true,a)};b.prototype.toString=function(){return Quark.UIDUtil.displayObjectToString(this)}})();
(function(){var b=Quark.Bitmap=function(a){this.image=null;this.rectHeight=this.rectWidth=this.rectY=this.rectX=0;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("Bitmap");this.image&&(this.setRect(a.rect||[0,0,this.image.width,this.image.height]),this.setDrawable(this.image));this._stateList.push("rectX","rectY","rectWidth","rectHeight")};Quark.inherit(b,Quark.DisplayObject);b.prototype.setRect=function(a){this.rectX=a[0];this.rectY=a[1];this.rectWidth=this.width=
a[2];this.rectHeight=this.height=a[3]};b.prototype.setImage=function(a){this.image=a;this.setDrawable(this.image)};b.prototype.render=function(a){a.draw(this,this.rectX,this.rectY,this.rectWidth,this.rectHeight,0,0,this.width,this.height)}})();
(function(){var b=Quark.DisplayObjectContainer=function(a){this.eventChildren=true;this.autoSize=false;this.children=[];a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("DisplayObjectContainer");this.setDrawable(a.drawable||a.image||null);if(a.children)for(var d=0;d<a.children.length;d++)this.addChild(a.children[d])};Quark.inherit(b,Quark.DisplayObject);b.prototype.addChildAt=function(a,b){if(b<0)b=0;else if(b>this.children.length)b=this.children.length;var c=this.getChildIndex(a);
if(c!=-1){if(c==b)return this;this.children.splice(c,1)}else a.parent&&a.parent.removeChild(a);this.children.splice(b,0,a);a.parent=this;if(this.autoSize){var c=new Quark.Rectangle(0,0,this.rectWidth||this.width,this.rectHeight||this.height),e=new Quark.Rectangle(a.x,a.y,a.rectWidth||a.width,a.rectHeight||a.height);c.union(e);this.width=c.width;this.height=c.height}return this};b.prototype.addChild=function(a){for(var b=this.children.length,c=0;c<arguments.length;c++)a=arguments[c],this.addChildAt(a,
b+c);return this};b.prototype.addChild2=function(a){for(var b=this.children.length,c=0;c<arguments.length;c++)a=arguments[c],this.addChildAt(a,b+c);return this};b.prototype.removeChildAt=function(a){if(a<0||a>=this.children.length)return false;var b=this.children[a];if(b!=null){var c=this.getStage();c!=null&&c.context.remove(b);b.parent=null}this.children.splice(a,1);return true};b.prototype.removeChild=function(a){return this.removeChildAt(this.children.indexOf(a))};b.prototype.removeAllChildren=
function(){for(;this.children.length>0;)this.removeChildAt(0)};b.prototype.getChildAt=function(a){return a<0||a>=this.children.length?null:this.children[a]};b.prototype.getChildIndex=function(a){return this.children.indexOf(a)};b.prototype.setChildIndex=function(a,b){if(a.parent==this){var c=this.children.indexOf(a);b!=c&&(this.children.splice(c,1),this.children.splice(b,0,a))}};b.prototype.swapChildren=function(a,b){var c=this.getChildIndex(a),e=this.getChildIndex(b);this.children[c]=b;this.children[e]=
a};b.prototype.swapChildrenAt=function(a,b){var c=this.getChildAt(a),e=this.getChildAt(b);this.children[a]=e;this.children[b]=c};b.prototype.getChildById=function(a){for(var b=0,c=this.children.length;b<c;b++){var e=this.children[b];if(e.id==a)return e}return null};b.prototype.removeChildById=function(a){for(var b=0,c=this.children.length;b<c;b++)if(this.children[b].id==a)return this.removeChildAt(b);return null};b.prototype.sortChildren=function(a){if(typeof a=="string")var b=a,a=function(a,e){return e[b]-
a[b]};this.children.sort(a)};b.prototype.contains=function(a){return this.getChildIndex(a)!=-1};b.prototype.getNumChildren=function(){return this.children.length};b.prototype._update=function(a){var b=true;this.update!=null&&(b=this.update(a));if(b!==false)for(var b=this.children.slice(0),c=0,e=b.length;c<e;c++){var f=b[c];f._depth=c+1;f._update(a)}};b.prototype.render=function(a){b.superClass.render.call(this,a);for(var d=0,c=this.children.length;d<c;d++)this.children[d]._render(a)};b.prototype.getObjectUnderPoint=
function(a,b,c,e){if(e)var f=[];for(var h=this.children.length-1;h>=0;h--){var g=this.children[h];if(!(g==null||!g.eventEnabled&&g.children==void 0||!g.visible||g.alpha<=0))if(g.children!=void 0&&g.eventChildren&&g.getNumChildren()>0){var k=g.getObjectUnderPoint(a,b,c,e);if(k)if(e)k.length>0&&(f=f.concat(k));else return k;else if(g.hitTestPoint(a,b,c)>=0)if(e)f.push(g);else return g}else if(g.hitTestPoint(a,b,c)>=0)if(e)f.push(g);else return g}return e?f:null}})();
(function(){var b=Quark.Stage=function(a){this.stageY=this.stageX=0;this.paused=false;this._eventTarget=null;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("Stage");if(this.context==null)throw"Quark.Stage Error: context is required.";this.bgLayer=new Q.Bitmap({id:"gameStagebg"});this.addChild(this.bgLayer)};Quark.inherit(b,Quark.DisplayObjectContainer);b.prototype.addPop=function(a){this.popChild=a;a.visible=false;a.id="gameStagePop";this.addChild(a)};b.prototype.setBgImg=
function(a){if(a instanceof Image)this.bgLayer.setImage(a),this.bgLayer.setRect([0,0,a.width,a.height]),this.bgLayer.visible=true};b.prototype.clear=function(){for(var a=0;a<this.children.length;a++){var b=this.children[a];b.id!="gameStagebg"&&b.id!="gameStagePop"&&this.removeChildAt(a)}};b.prototype.removeAllChildren=function(){this.clear()};b.prototype.step=function(a){this.paused||(this.popChild&&this.popChild.visible==true&&this.setChildIndex(this.popChild,this.children.length-1),this.bgLayer.image&&
this.bgLayer.visible==true&&this.setChildIndex(this.bgLayer,0),this._update(a),this._render(this.context))};b.prototype._update=function(a){for(var b=this.children.slice(0),c=0,e=b.length;c<e;c++){var f=b[c];f._depth=c+1;f._update(a)}this.update!=null&&this.update(a)};b.prototype._render=function(a){a.clear!=null&&a.clear(0,0,this.width,this.height);b.superClass._render.call(this,a)};b.prototype._onEvent=function(a){var d=a.pageX||a.clientX,c=a.pageY||a.clientY,d=(d-this.stageX)/this.scaleX,c=(c-
this.stageY)/this.scaleY,e=this.getObjectUnderPoint(d,c,true),f=this._eventTarget;a.eventX=d;a.eventY=c;d=a.type=="mouseout"&&!this.context.canvas.contains(a.relatedTarget);if(f!=null&&(f!=e||d))a.lastEventTarget=f,(c=d||e==null||a.type=="mousemove"?"mouseout":a.type=="touchmove"?"touchout":null)&&f._onEvent({type:c}),this._eventTarget=null;if(e!=null&&e.eventEnabled&&a.type!="mouseout")a.eventTarget=this._eventTarget=e,e._onEvent(a);(d||a.type!="mouseout")&&b.superClass._onEvent.call(this,a)}})();
(function(){var b=Quark.ImageLoader=function(a){b.superClass.constructor.call(this);this.loading=false;this._index=-1;this._loaded=0;this._images={};this._totalSize=0;this._maxConnections=1;this._currentLoadsLen=-1;this._addSource(a)};Quark.inherit(b,Quark.EventDispatcher);b.prototype.load=function(a){this._addSource(a);a.length==0?this.dispatchEvent({type:"complete",target:this,images:this._images}):this.loading||this._loadNext()};b.prototype.setMaxConnections=function(a){this._maxConnections=a};
b.prototype._addSource=function(a){if(a){for(var a=a instanceof Array?a:[a],b=0;b<a.length;b++)this._totalSize+=a[b].size||0;this._source=this._source?this._source.concat(a):a}};b.prototype._loadNext=function(){this._index++;this._load(this._index)};b.prototype._load=function(a){if(!(a>=this._source.length)){var b=new Image;b.onload=Quark.delegate(this._loadHandler,this,a,b);b.src=this._source[a].src;this._currentLoadsLen++;this.loading=true}};b.prototype._loadHandler=function(a,b){this._loaded++;
var c=this._source[a];c.image=b;this._images[c.id||c.src]=c;this.dispatchEvent({type:"loaded",target:this,image:c});this._currentLoadsLen=Math.max(this._currentLoadsLen-1,0);this._loaded<this._source.length?this._loadNext():(this._source=[],this.loading=false,this._index=-1,this.dispatchEvent({type:"complete",target:this,images:this._images}))};b.prototype.getLoaded=function(){return this._loaded};b.prototype.getTotal=function(){return this._source.length};b.prototype.getLoadedSize=function(){var a=
0,b;for(b in this._images)a+=this._images[b].size||0;return a};b.prototype.getTotalSize=function(){return this._totalSize}})();
(function(){var b=Quark.MovieClip=function(a){this.interval=0;this.useFrames=this.paused=false;this.currentFrame=0;this._frames=[];this._frameLabels={};this._frameDisObj=null;this._displayedCount=0;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("MovieClip");a.frames&&this.addFrame(a.frames)};Quark.inherit(b,Quark.Bitmap);b.prototype.addFrame=function(a){var b=this._frames.length;if(a instanceof Array)for(var c=0;c<a.length;c++)this.setFrame(a[c],b+c);else this.setFrame(a,
b);return this};b.prototype.setFrame=function(a,b){b==void 0||b>this._frames.length?b=this._frames.length:b<0&&(b=0);this._frames[b]=a;a.label&&(this._frameLabels[a.label]=a);if(a.interval==void 0)a.interval=this.interval;b==0&&this.currentFrame==0&&this.setRect(a.rect)};b.prototype.getFrame=function(a){return typeof a=="number"?this._frames[a]:this._frameLabels[a]};b.prototype.play=function(){this.paused=false};b.prototype.stop=function(){this.paused=true};b.prototype.gotoAndStop=function(a){this.currentFrame=
this.getFrameIndex(a);this.paused=true};b.prototype.gotoAndPlay=function(a){this.currentFrame=this.getFrameIndex(a);this.paused=false};b.prototype.getFrameIndex=function(a){if(typeof a=="number")return a;for(var a=this._frameLabels[a],b=this._frames,c=0;c<b.length;c++)if(a==b[c])return c;return-1};b.prototype.nextFrame=function(a){var b=this._frames[this.currentFrame];if(b.interval>0)a=this._displayedCount+a,this._displayedCount=b.interval>a?a:0;if(b.jump>=0||typeof b.jump=="string")if(this._displayedCount==
0||!b.interval)return this.currentFrame=this.getFrameIndex(b.jump);return b.interval>0&&this._displayedCount>0?this.currentFrame:this.currentFrame>=this._frames.length-1?this.currentFrame=0:++this.currentFrame};b.prototype._update=function(a){var d=this._frames[this.currentFrame];d.stop?this.stop():(this.paused||this.nextFrame(this.useFrames?1:a&&a.deltaTime),this.setRect(d.rect),b.superClass._update.call(this,a))};b.prototype.render=function(a){var b=this._frames[this.currentFrame].rect;a.draw(this,
b[0],b[1],b[2],b[3],0,0,this.width,this.height)}})();
(function(){var b=Quark.Button=function(a){this.state=b.UP;this.enabled=true;a=a||{};b.superClass.constructor.call(this,a);this.id=a.id||Quark.UIDUtil.createUID("Button");this._skin=new Quark.MovieClip({id:"skin",image:a.image});this.addChild(this._skin);this._skin.stop();this.eventChildren=false;if(a.useHandCursor===void 0)this.useHandCursor=true;a.up&&this.setUpState(a.up);a.over&&this.setOverState(a.over);a.down&&this.setDownState(a.down);a.disabled&&this.setDisabledState(a.disabled)};Quark.inherit(b,
Quark.DisplayObjectContainer);b.UP="up";b.OVER="over";b.DOWN="down";b.DISABLED="disabled";b.prototype.setUpState=function(a){a.label=b.UP;this._skin.setFrame(a,0);this.upState=a;return this};b.prototype.setOverState=function(a){a.label=b.OVER;this._skin.setFrame(a,1);this.overState=a;return this};b.prototype.setDownState=function(a){a.label=b.DOWN;this._skin.setFrame(a,2);this.downState=a;return this};b.prototype.setDisabledState=function(a){a.label=b.DISABLED;this._skin.setFrame(a,3);this.disabledState=
a;return this};b.prototype.setEnabled=function(a){if(this.enabled==a)return this;(this.eventEnabled=this.enabled=a)?this._skin.currentFrame==3&&this._skin.gotoAndStop(b.UP):this.disabledState?this._skin.gotoAndStop(b.DISABLED):this._skin.gotoAndStop(b.state.UP);return this};b.prototype.changeState=function(a){if(this.state!=a){this.state=a;switch(a){case b.OVER:case b.DOWN:case b.UP:if(!this.enabled)this.eventEnabled=this.enabled=true;this._skin.gotoAndStop(a);break;case b.DISABLED:this.setEnabled(false)}return this}};
b.prototype._onEvent=function(a){if(this.enabled){switch(a.type){case "mousemove":this.overState&&this.changeState(b.OVER);break;case "mousedown":case "touchstart":case "touchmove":this.downState&&this.changeState(b.DOWN);break;case "mouseup":this.overState?this.changeState(b.OVER):this.changeState(b.UP);break;case "mouseout":case "touchout":case "touchend":this.upState&&this.changeState(b.UP)}b.superClass._onEvent.call(this,a)}};b.prototype.setDrawable=function(){b.superClass.setDrawable.call(this,
null)}})();
(function(){var b=Quark.Text=function(a,d){this.text=""+a;this.fontSize="12px";this.fontFamily="sans-serif";this.fontStyle=this.fontWeight="normal";this.color="#000";this.textAlign="start";this.outline=false;this.maxWidth=1E4;this.lineWidth=null;this.lineSpacing=d.lineSpacing||12;this.fontMetrics=null;this.textHeight=this.textWidth=0;d=d||{};d.eventEnabled=false;b.superClass.constructor.call(this,d);this.id=Quark.UIDUtil.createUID("Text");typeof this.fontSize=="number"&&(this.fontSize+="px");this.lineWidth=
d.lineLength||this.lineWidth;this.font=[this.fontWeight,this.fontSize,this.fontFamily].join(" ")};Quark.inherit(b,Quark.DisplayObject);b.prototype.setText=function(a){this.text=""+a};b.prototype._draw=function(a){if(this.text&&this.text.length!=0){a.font=this.font;a.textAlign=this.textAlign;a.textBaseline="top";this.outline?a.strokeStyle=this.color:a.fillStyle=this.color;var b=this.text.split(/\r\n|\r|\n|<br(?:[ \/])*>/),c=-4;this.width=this.lineWidth||0;if(this.lineHeight==void 0)this.lineHeight=
a.measureText("\u4e2d").width*1.2+this.lineSpacing;for(var e=0,f=b.length;e<f;e++){var h=b[e],g=a.measureText(h).width;if(this.lineWidth==null||g<this.lineWidth){if(g>this.width)this.width=g;this._drawTextLine(a,h,c)}else{for(var h=h.split(/([^\x00-\xff]|\b)/),g=h[0],k=1,j=h.length;k<j;k++){var i=h[k];i&&i.length!=0&&(a.measureText(g+i).width>this.lineWidth?(this._drawTextLine(a,g,c),c+=this.lineHeight,g=i):g+=i)}this._drawTextLine(a,g,c)}c+=this.lineHeight}this.height=c}};b.prototype._drawTextLine=
function(a,b,c){var e=0;switch(this.textAlign){case "center":e=this.width*0.5;break;case "right":e=0-this.width;break;case "end":e=this.width}this.outline?a.strokeText(b,e,c):a.fillText(b,e,c)};b.prototype.getTextWidth=function(){return this.width>0?this.width:this.textWidth};b.prototype.getText=function(){return this.text}})();
